# Name der Anwendung
APPLICATION = hello-world

# Wenn beim Aufruf von “make”, kein Board angegeben wurde, verwende
# “native”
BOARD ?= native

# Pfad zur RIOT installation, in diesem Fall befindet sich RIOT im 
# User Home verzeichnis
RIOTBASE ?= ${CURDIR}/../.base

include $(RIOTBASE)/Makefile.include