# Name der Anwendung
APPLICATION = commands-tutorial

# Wenn beim Aufruf von "make", kein Board angegeben wurde, verwende
# "native"
BOARD ?= native

# Hinzufügen der benötigten Module shell und shell_commands
USEMODULE += shell
USEMODULE += shell_commands

# Pfad zur RIOT installation, in diesem Fall befindet sich RIOT im
# User Home verzeichnis
RIOTBASE ?= ${CURDIR}/../.base

include $(RIOTBASE)/Makefile.include