# Name der Anwendung
APPLICATION = aes_ecb_example

# Standardboard
BOARD ?= native

USEMODULE += shell			# RIOT Shell Modul
USEMODULE += shell_commands # RIOT Shell Commands
USEMODULE += crypto_aes		# Verschlüsselung mithilfe von AES
USEMODULE += od				# Object Dump

# Pfad zur RIOT installation
RIOTBASE ?= ${CURDIR}/../.base

include $(RIOTBASE)/Makefile.include
